### ISSUE TITLE
About the Pin's shape and Node's icon

### ISSUE THREAD

**Issue by ketoo** [Nelarius/imnodes#17]
Now we PushColorStyle function to change the color for node and pin.

How about adding a way to support to change the shape of Pin? We could get a good result if we can change the shape when using the node system with some of the basic shapes listed below:

PinShape
{
    CIRCLE,
    TRIANGLE,
    SQUARE,
    PENTAGON,
    STAR,
    SEMICIRCLE,
    HEX,
    CROSS,
    RING,
    ARROW,
    QUATREFOIL,
    RHOMBUS,
    HEART,
    OCTAGON,
};

Besides, it would be great if there have a way to change the node's icon like this:

![](https://ludiq.io/assets/images/Flow-New.png)

**Comment by Nelarius** [comment]
Nice inspiration pic! This is Unity's visual scripting system, right?

* New pin shapes should be doable. ImGui's draw API already supports a few of those shapes out of the box, and I guess some of those can be composed to create more complex shapes
* Adding icons to the title text bar is somewhat more non-trivial. The top of the node is just a rectangle with text -- I will have to see if there is a convenient way to display icons using ImGui
* I actually really like the pins being outside of the nodes, I might have to add some more customization options for this 😄

**Comment by ketoo** [comment]
> Nice inspiration pic! This is Unity's visual scripting system, right?
> 
> * New pin shapes should be doable. ImGui's draw API already supports a few of those shapes out of the box, and I guess some of those can be composed to create more complex shapes
> * Adding icons to the title text bar is somewhat more non-trivial. The top of the node is just a rectangle with text -- I will have to see if there is a convenient way to display icons using ImGui
> * I actually really like the pins being outside of the nodes, I might have to add some more customization options for this 😄


Yes, it's a plugin named "bolt" and now on sale in the unity store.

If you like the pins being outside of the nodes, one more good idea is to add an icon for pins which like add an icon for nodes.

SetPinIcon(int pin, char* iconPath);
SetNodeIcon(int pin, char* iconPath);

Besides, if we can add an arrow for links and could set the width that would be great as sometimes we need to let developers know which is the main workflow in one second.

**Comment by ketoo** [comment]
![image](https://user-images.githubusercontent.com/5752768/72972231-ee436280-3e2f-11ea-8af0-3f71cf1e4b73.png)

Above is what I am working, if we have the  arrow for links which can make developers
 understand the workflow easier.

**Comment by Nelarius** [comment]
Thanks for posting the picture, cool to see what your blueprint system looks like!

I agree though, blueprint systems tend to have more symbology embedded in the nodes than what `imnodes` currently offers. I'm using `imnodes` for a fairly simple graphics editor, so I have somewhat neglected this aspect of the library.

I created an issue for new pin shapes, because I have a fairly good idea of how to do that.

Regarding icons adjacent to the pins, you might want to try `ImGui::Image`. The attribute blocks should let you put anything in there, including images. Incidentally, I'm thinking that this might be one way of getting icons into the title bar -- generalizing the title bar to let users place their own text and images there. I will have to do some tests for this. One of my goals is to keep the `imnodes.h` interface fairly simple, while not restricting the user too much.

**Comment by ketoo** [comment]
I have finished this feature and submitted a PR with a picture. https://github.com/Nelarius/imnodes/pull/20
