### ISSUE TITLE
The length of ImGui::Separator() not correct

### ISSUE THREAD

**Issue by ketoo** [Nelarius/imnodes#25]
The issue showed as below:

![image](https://user-images.githubusercontent.com/5752768/75968183-dc2a0900-5f31-11ea-8474-fc71347556a8.png)

The length of the line should the same length as the window.

**Comment by Nelarius** [comment]
Oh shoot, I'm not sure I have a good solution for this right now 😰 

When `ImGui::Separator` is called, we don't yet know the size of the node because `imnodes::EndNode` hasn't been called yet. So the `ImGui::Separator` call uses the size of the current window, which is the canvas, I guess? 😬 

I will have to create a list of known issues or something, and add this there until I can figure out what to do about this.

**Comment by Nelarius** [comment]
Added a mention of this in the README for now, thanks for reporting this!

**Comment by ketoo** [comment]
Thanks, I use a small button to meet the same goal.

**Comment by hiroMTB** [comment]
This can be solved by similar approach like https://github.com/Nelarius/imnodes/issues/167#issuecomment-1742109937


But for Separator() we overwrite `window->Size.x`

```
ImGuiWindow* window = ImGui::GetCurrentWindow();
  
int xbackup = window->Size.x;
window->Size.x = window->DC.CursorPos.x + width;

ImGui::Separator();

// don't forget to tidy up
window->Size.x = xbackup;

```

I tested and can confirm it works but somehow Separator's line became slightly longer than node width like 10%.
It might be good to do this overwrite window variable inside BeginNode() so that all imgui widgets work fine until imgui officially supports this kind of feature.
