### ISSUE TITLE
Expected '(' for function-style cast or type construction

### ISSUE THREAD

**Issue by andrewssobral** [Nelarius/imnodes#30]
Thanks for this nice project.
However,  I had this issue while building the project [multieditor] with XCode:

![image](https://user-images.githubusercontent.com/483114/79119706-4c2d7980-7d91-11ea-9305-d1ff07c696cc.png)

**Comment by Nelarius** [comment]
Hi @andrewssobral !

What version of clang are you using in Xcode? It looks like c++11 is either not supported or is disallowed in the build for `multieditor` project for some reason 🤔 I was able to reproduce this problem by  manually disallowing c++11 in my local makefile build.

For now, I've added a constructor to `Node` in the commit `ff8fe0f`. It might still not work, because I use range-based for loop in a couple places in the examples.

**Comment by andrewssobral** [comment]
Thank you @Nelarius for your quickly feedback.
I am using XCode 10.1, I added the following line:
`buildoptions { "-std=c++1z" }`
inside `premake5.lua`, and now it's working fine!
![image](https://user-images.githubusercontent.com/483114/79232478-d6e0a800-7e67-11ea-8580-c8800678657f.png)
