### ISSUE TITLE
Feature request: Zoom

### ISSUE THREAD

**Issue by nrzimmermann** [Nelarius/imnodes#37]
A zoom feature would be really useful for large node graphs. Are you planning to implement this? Or maybe some other option for faster navigation through the graph?

**Comment by Nelarius** [comment]
I haven't planned on adding zooming, since I _think_ it requires a modified version of ImGui 🤔 See this discussion for more: https://github.com/ocornut/imgui/issues/772#issuecomment-244512595 I do want to try the fringe-scale imgui modification out though, just to see how zooming could work with imnodes & to document the process.

If you want a way to faster jump between nodes now, you could use `EditorContextResetPanning` to have the editor window jump to specific nodes when, for example, navigating between nodes using arrow keys.

**Comment by ketoo** [comment]
void EditorContextMoveToNode(const int node_id);

This way can reduce your pain....

**Comment by nrzimmermann** [comment]
Ok! Jumping between nodes like that might be a good solution for now, thank you!

**Comment by Nelarius** [comment]
I'll close this issue for now 🙂
