### ISSUE TITLE
Zooming in/out

### ISSUE THREAD

**Issue by SocketByte** [Nelarius/imnodes#51]
Any plans in the future for zooming in and out? Would be really useful. Love your work, cheers!

**Comment by Nelarius** [comment]
Hi @SocketByte ! I am planning on looking in to how zooming in and out could work in imnodes on some level, since this is the most requested feature 🙂 

In the meanwhile, you can check this discussion [discussion](https://github.com/ocornut/imgui/issues/772#issuecomment-244628219) about thedmd's node zoom implementation. It probably can't be implemented in imnodes directly, as it's an ImGui modification.

**Comment by francesco-cattoglio** [comment]
@Nelarius Is there any plan for implementing some zooming functionality in the near future? If yes, I would be interested in helping with it! Since I will need such a feature soon I will have to implement something anyway, so this looks like a good chance to contribute to the project.
