### ISSUE TITLE
Node in the front won't move if a node containing an ImGui widget with is behind it.

### ISSUE THREAD

**Issue by francesco-cattoglio** [Nelarius/imnodes#73]
If the editor contains two nodes, clicking and dragging on the one in the front won't be possible if an imgui widget is behind your mouse cursor, and you will be interacting with that widget instead, even if you cannot see it. I noticed it when playing around with sliders. You can also still interact with the pins of the node behind the one shown. Perhaps it is related to the changes in this commit? https://github.com/Nelarius/imnodes/commit/fd96ac2f176c88fc55b01894acfb4b7862e41b8d

**Comment by Nelarius** [comment]
Clicking and dragging nodes when an imgui widget is behind the mouse cursor was fixed in this commit: https://github.com/Nelarius/imnodes/commit/e8f8281b15a043c7faaaf7bcfc8cc3724ce6d960

Interacting with pins when a node is occluding them is getting fixed: https://github.com/Nelarius/imnodes/issues/84

**Comment by Nelarius** [comment]
Interacting with occluded pins was fixed in 50a696d1c8a22ad25e2a84d8a9fb1a181d5b60da
