### ISSUE TITLE
PR#95 namespace collision

### ISSUE THREAD

**Issue by sonoro1234** [Nelarius/imnodes#97]
Sorry for not realizing this earlier: namespace ImNodes will collide with https://github.com/rokups/ImNodes/blob/02b085dace8bdd815374d6440efb1f70d8a9ebaf/ImNodes.h#L35

**Comment by Nelarius** [comment]
Drat 😰 Is this preventing you from using the library in a project? Assuming you're using both libraries in the same project? Or is this preventing code generation in cimgui?

**Comment by sonoro1234** [comment]
LuaJIT-ImGui is including cimnodes for Nelarius/imnodes and cimnodes_r for rukups/ImNodes (with namespace ImNodes).  I have not tried but I guess that cimnodes generation will succed but using both libraries (as LuaJIT-ImGui does) is open to namespace clashes.

**Comment by Nelarius** [comment]
Oh right, I hadn't thought about the LuaJIT-ImGui use case at all 🤔 Wondering what the options here are.
- Doing nothing and keeping things the way they are opens the door to problems in LuaJIT-ImGui
- Reverting the namespace back to `imnodes`. It's inconsistent with the enum constants though, and I really like the way enum constant usage is consistent with ImGui now
- Something a bit silly, like changing the namespace to `Imnodes` in order to be consistent with the CamelCase naming used elsewhere

A bit unfortunate that our two projects have the exact same name 😂 I think @rokups was first, so maybe I should call this ImNodes2 or something 😄

**Comment by rokups** [comment]
Ehm but why is this a problem? I doubt anyone is going to use both libraries in same codebase.

**Comment by sonoro1234** [comment]
> Ehm but why is this a problem? I doubt anyone is going to use both libraries in same codebase.

I am doing it in LuaJIT-ImGui

**Comment by sonoro1234** [comment]
> ImNodes2 or something

ImNodesN ?

**Comment by Nelarius** [comment]
As unfortunate as the namespace collision is, I'll keep things as they currently are 😞 I never really intended this to be used in the same codebase as other node editors.
